package com.concreteitsolutions.sms.model;

public enum SMSStatusCode {

	SUCCESS(0),
	EMPTY_LOGIN_FIELD(1),
	EMPTY_PASSWORD_FIELD(2),
	WRONG_CREDENTIALS(3),
	EMPTY_MESSAGE(4),
	SHOULD_NOT_EXCEED_160_CHARAC(5),
	SHOULD_ENTER_PHONE_NUMBER(6),
	PHONE_NUMBER_SHOULD_BE_10_DIGITS(7),
	BLACK_LISTED_PHONE_NUMBER(11),
	MT_CREDIT_USED_UP(12),
	UNAUTHORIZED_IP_ADDRESS(14),
	SHOULD_GIVE_SEND_CHANNEL(15),
	EMPTY_SENDER_FIELD(16),
	SENDER_FIELD_SHOULD_BE_BETWEEN_3_AND_11_CHARAC(17),
	SENDER_FIELD_SHOULD_NOT_CONTAIN_ONLY_DIGITS(18),
	MESSAGE_SHOULD_NOT_EXCEED_148_CHARAC_WHEN_SENDER_FIELD_IS_GIVEN(19),
	PHONE_NUMBER_NOT_EXISTING(21),
	PHONE_NUMBER_CORRESPONDING_TO_FULL_MVNO(22),
	MAX_SMS_RECEIVER_PER_REQUEST_IS_500(23),
	NO_COMMERCIAL_SMS_BETWEEN_20H_AND_08H_NOR_SUNDAY_OR_BANK_HOLIDAY(19),
	PHONE_NUMBER_0899_PRICE_INFORMATION_ERROR(25),
	PHONE_NUMBER_0892_PRICE_INFORMATION_ERROR(26),
	PHONE_NUMBER_AREA_CODE_NOT_AUTHORIZED(27),
	QUALIFICATION_CREDIT_USED_UP(28),
	CAN_NOT_PERFORM_OPERATION_OVERFLOW(29),
	DOMAIN_CONNECTION_ERROR(30),
	MESSAGE_SHOULD_NOT_EXCEED_X_CHARACS(31),
	GAP_BETWEEN_SMS_LENGTH_AND_EXPECTED_LENGTH(32),
	UNAUTHORIZED_SENDER(33),
	SMS_LONG_FIELD_SHOULD_BE_INTEGER(34),
	HLR_CREDIT_USED_UP(35),
	NOT_AUTHORIZED_TO_REMOVE_STOP_MESSAGE(36),
	PHONE_NUMBERS_NOT_FROM_SAME_COUNTRY(37),
	SMS_SHOULD_NOT_EXCEED_X_CHARACS(38),
	SMS_SHOULD_NOT_EXCEED_y_CHARACS(39),
	UCS2_FORMAT_MESSAGE_NOT_SUPPORTED_IN_FRANCE(40),
	HLR_AUTHORIZATION_VIOLATION(41),
	SENDER_SHOULD_NOT_CONTAIN_SPECIAL_CHARACS(42),
	SENT_DATE_SHOULD_BE_TO_FORMAT_AAAA_MM_JJ_HH_MM(43),
	PHONE_REPOSITORY_SUCCESSFULLY_CREATED(100),
	SHOULD_ENTER_PHONE_REPOSITORY_NAME(101),
	UNKNOWN_PHONE_REPOSITORY_ID(102);

	/**
	 * TODO FINISH ENUM MAPPING ..
	 */

	private final int code;

	SMSStatusCode(final int code) {
		this.code = code;
	}
}
